### ISSUE TITLE
[BackEnd]Controllers&Services

### ISSUE THREAD

**Issue by MaximDragosAndrei** [MaximDragosAndrei/fiimem#4]
Mai trebuie facute controllere-le si service-uri pentru restul tabelleor din baza de date.
In incarcarile anterioare este un model pentru un tabel.
Ar trebui facut un PACHET nou care sa contina:
- O clasa ce modeleaza o intrare din tabel
- Controller-ul pentru clasa respectiva (va apela functii definite in sevice)
- Sevrvice-ul ce contine functii apelate in controller (ex: getAll<Objects>, get<Objects> etc.)

**Comment by samson-georgiana** [comment]
Il rezolv eu.
